### PR TITLE
Cleanup configuration code

### PR DESCRIPTION
**Pull request by SuperQ**
* Set defaults to avoid ignoring config errors.
* Use `bool` for config flags where appropriate.
* Fix ignored `i2c_device` config.
* Remove unused UMTS config section.
* Cleanup `bak` file.
* Use go-style CamelCase for struct names.

### CODE REVIEW

**Comment by SuperQ** [comment]
CC @Trickx 

Fixes: https://github.com/nDenerserve/SmartPi/issues/27

**Comment by nD-enerserve** [comment]
I think thats wrong:
-       if c.MeasureVoltage1 == 0 || values[4] < 10 {
 +	if c.MeasureVoltage1 || values[4] < 10 {

**Comment by SuperQ** [comment]
@nD-enerserve Did that `c.MeasureVoltage1` test ok?

**Comment by nD-enerserve** [comment]
`if !c.MeasureVoltage1 || values[4] < 10 {`
is right. Problem is fixed.

**Comment by SuperQ** [comment]
Thanks, I saw the fix in master.

**Pull request merged**
