### PR TITLE
Refactor readout code

### PR DESCRIPTION
**Pull request by SuperQ**
Major refactor of the readout code.  Use a struct to handle readout data, makes the code less error prone.

* Pass struct to reduce allocations.
* Fix bug in power factor calcuations.
* Update use of value data to new struct.
* Operate on one phase at a time to better correlate instantaneous readings.
* Measure at least 3 cycles at 50Hz or 4 cycles at 60Hz.
* Move frequency measurement to last item in measurement list.

### CODE REVIEW

**Comment by Trickx** [comment]
Hi Ben,

I can't deny myself to mention, that you have just proven that these changes are not less error prone.
The old code looped through the readings.
Isn't there a way in Go the iterate through the readings?
Maintenance of repeated code is always annoying.

**Comment by SuperQ** [comment]
@Trickx My next work was to replace the accumulator array with a struct as well.  Then it's possible to loop over the phases.  As you can see by [this commit](https://github.com/nDenerserve/SmartPi/pull/78/commits/c69f097030caa7df9a60336ddcc269b95acae5b0), it's possible to do the loops as you suggest.

**Comment by SuperQ** [comment]
@Trickx I have an idea to fix the MQTT topics as well, I need to implement a little helper function, should be easy enough.

**Comment by Trickx** [comment]
Yes, it should easy to write a wrapper to generate the MQTT topics in an iterative manner.
We could consider changing topic name to match the struct names.
Howver, this would break backward compatibility.

**Comment by SuperQ** [comment]
@Trickx Ok, I added the helper function to loop over the phases and publish the topics, while maintaining the existing naming convention compatibility.

**Comment by SuperQ** [comment]
Ok, I've finished up this refactor.  I've replaced several of the static lists with loops over each phase.

**Pull request merged**
