### PR TITLE
- Refactored MQTT: Moved into exporterMQTT.go to cleanup readout.go

### PR DESCRIPTION
**Pull request by Trickx**
- Replaced logging functions
- TODO: Define generic interface for all exporters
- WISH: Prometheus and other data exporters to be moved from readout.go into their own file "exporterXYZ.go"

### CODE REVIEW

**Comment by SuperQ** [comment]
This change doesn't make a lot of sense, as the the MQTT functions aren't used by anything but the readout binary.  Therefore they don't need to be moved out of the main package.

Or really, if there is a desire to move some of the readout functionality into a new package, it should be a separate `readout` package, and not lumped in with all of the other more generic `smartpi` functions.

There is also an unrelated and undocumented in the commit that violates typical Go programming style, which is to declare vars and such close to where they are used, rather than pushed to the top of files.

**Comment by Trickx** [comment]
I'm fine to move the code into the package "main", but still in a different file.
I see no difference to e.g. ade7878.go, which is also used by readout.go, only.
The intention is to keep readout.go smart and clean.
Let's assume some other contributiors add 10 more exporters.
readout.go would grow endlessly and would become messy - as it already started.
This is why I moved the MQTT stuff into a different file.

These const and var definitions were hidden inside some func definition.
I just collected them at one place. Feel free to re-sort them, but keep them together.
What if a variable is used in multiple functions?
Where to declare it? This is why I think at the beginning of a file makes most sense.
C/C++/Java style conventions do follow.
Where did you find information that golang has a different style convention and why?

**Comment by Trickx** [comment]
Regarding packaging, I agree with you that it belongs together.
The logic consequence is to move readout.go into the package smartpi, where it belongs to.

**Comment by Trickx** [comment]
Regarding location of declarations, I would liek to refer towards the go sources itself.
"format.go" might be a useful example:
https://github.com/golang/go/blob/master/src/fmt/format.go
All definitions of constants and type are at the beginning of the file.

However, there are also other example, like in log.go:
https://github.com/golang/go/blob/master/src/log/log.go

The variable `std` is defined in line 73, after the first function.
I have no idea why the function `func (l *Logger) SetOutput(w io.Writer)` was placed before.
`std` is used the first time in function `func SetOutput(w io.Writer)` at line 254.

My programming experience is based on C++ and Java.
I'm a newbie to go. Please teach me why your proposed pattern in go looks to me like the re-invention of the wheel, just somewhat angular.

Don't get me wrong, my purpose is to contribute and push smartpi forward.

**Comment by SuperQ** [comment]
I'm also a bit of a Go newbie.  The recommendation for "declare where used" comes from other much more experienced Go developers on the projects I normally work on.  I haven't found an official style guide that says this, I will prod them into explaining it.

As for what things should go in which packages, you always need a `main` package in order to build binaries, so it's not possible to move everything to `smartpi`.

The `smartpi` functions for the data gathering make sense to stay where they are.  We could add an additional package for the readout exporters called `exporter`.

Then the source would be `src/readout/exporter/mqtt.go` for example.  This would be a nice organization.  But the code isn't that complicated as-is, so why I suggested we just keep it all in the `main` package, but split up the code into separate files.

**Comment by nD-enerserve** [comment]
That's nice. Then we are all quite new in Go.
My suggestion is that we run all exporter as stand-alone programs. The current values can be taken from the shared file. Whenever the file changes, the respective program can process the data. File monitoring might be https://github.com/fsnotify/fsnotify.
So we would follow the approach: small programs for small tasks.

**Comment by SuperQ** [comment]
A shared file is a very bad idea, and makes the code even more complicated.  The current method is much simpler, we just need to structure the code such that it's easier to maintain.

**Pull request closed without merging**
