### PR TITLE
Increase readout sampling frequency

### PR DESCRIPTION
**Pull request by SuperQ**
Increase readout sampling frequency from 5000ms to 1000ms.
* Update accumulator data and metrics endpoint every second.
* Update shared files and MQTT every 5 seconds.
* Update database every 60 seconds.
* Simplify accumulator data update case statement.

### CODE REVIEW

**Comment by SuperQ** [comment]
Here's a nice sample of the data while my water kettle is on.  You can also see the small bump of 100W when I'm using the coffee grinder after the first phase of the kettle's cycle.  The kettle uses a PID-style warmup in order to bring the water up to 95C, rather than go full-boil.
smartpi-1s-water-kettle

**Comment by Trickx** [comment]
I like the idea to increase measurement rate, if performance is not as issue.

This pull request introduces different, non-configurable, publication rates for the data:
-	1s	updatePrometheusMetrics(valuesr)
-	5s	writeSharedFile(config, valuesr) 
-	5s	publishMQTTReadouts(config, mqttclient, valuesr)
-	60s	updateSQLiteDatabase(config, data)
-	60s	updateCounterFile(…)

Architecture wise, it become more messy again.
-	All data exporter should decide by themselves how often data is published.
-> configuration handling inside the exporter, not within main
-	Data exporter may would like to implement an averaging function if data aggregation rate is faster than publication rate.

We should consider a generic approach for all exporter.

**Comment by SuperQ** [comment]
This doesn't hinder any architecture changes.

Re-architecting the updates is now slightly easier, as we have a single main loop that polls the instant values into valuesr, and keeps the 1min averaging/cumulative counters updated.

The prometheus update method is the only thing close to where we would want to go, as it simply accepts updates at any rate, and stores the values for later consumption at whatever the external service needs them.

@Trickx You keep saying we should consider a generic approach, without a proposal for an actual code pattern.  Until we have that code pattern, there's no point in discussing it.

**Comment by SuperQ** [comment]
From a performance perspective, it uses a bit more CPU time, but is still trivial.  On my Pi3, it went from 0.5% to 2.25% of a single core.
smartpi-cpu

**Pull request merged**
